name: CI

on:
  pull_request:

jobs:
  game-server-build:
    name: Game Server Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build game-server Docker image
      run: docker build . -f ./game_server.Dockerfile
  website-build:
    name: Website Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build website Docker image
      run: docker build . -f ./website.Dockerfile
  # build-assets:
  #   name: Build game assets
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./agot-bg-game-server
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: 16
  #   - name: Install dependencies
  #     run: yarn install --frozen-lockfile
  #   - name: Build assets
  #     run: yarn run generate-json-schemas && yarn run build-client
